### ISSUE TITLE
Update UML Diagrams in DG

### ISSUE THREAD

**Issue by Jasperabez** [AY2425S1-CS2103-F13-2/tp#112]
As part of this week's TP, can be done after release
Proposed Distribution
UI  component: @kahsuann, @hanscau 
Model component: @kevin-pek, @Jasperabez 
Storage component: @C5hives
Left out Logic component as not much changed (help verify this @C5hives)

**Comment by C5hives** [comment]
Yeah, the `Logic` component hasn't been changed much except for us adding a whole ton of getters (which are mostly utilised in UI)

**Comment by C5hives** [comment]
Some UML diagrams might still need changing since there are still PRs still open.
