### ISSUE TITLE
Set aliases for commands

### ISSUE THREAD

**Issue by Jasperabez** [AY2425S1-CS2103-F13-2/tp#113]
@C5hives favorite feature, set aliases to current commands
Tasks:
1. Parser and command for set Alias
2. Alias middleware between parser and command
3. Storage for aliases

**Comment by Jasperabez** [comment]
@C5hives assigned @kahsuann to tackle this issue together so that the weekly Tp individual participation can be met

**Comment by C5hives** [comment]
Only if time permits! There might be other more important features that are nicer to have than this one.

**Comment by C5hives** [comment]
Incredibly unlikely we will have the bandwidth to tackle this. As such, closing this issue.
