### ISSUE TITLE
Rework Edit Command to make use of new standardized format

### ISSUE THREAD

**Issue by Jasperabez** [AY2425S1-CS2103-F13-2/tp#115]
Edit command have not been reworked to modify vendor and events through the `\v \e` format

Parent Issue: #77 

Although labeled as Medium, is more of a High as our options are either to rework it or remove it

**Comment by C5hives** [comment]
Should a separate issue for adding event deletion functionality be created? It's required to address this issue (unless it's intended to be lumped together as a single issue?)

**Comment by C5hives** [comment]
> Should a separate issue for adding event deletion functionality be created? It's required to address this issue (unless it's intended to be lumped together as a single issue?)

Forgotten that deletion has already been implemented. Disregard!
