### ISSUE TITLE
Revamp unassign from View Mode for nested event/vendor list

### ISSUE THREAD

**Issue by Jasperabez** [AY2425S1-CS2103-F13-2/tp#116]
Unassign in view mode when passed in the index of the associated event/vendor should work, or index should be removed.

Possible solutions:
- Index made to match with filtered list
OR
- In view mode unassign should be overloaded such that it looks for nested list first (if index collides with both nested and left side list should throw error?)
OR
- if `e/` or `v/` (whichever one is being viewed) is not given then reference from nested else follow default behaviour
OR
- or assignable list have no assigned events, and unassign would only look at assigned in view mode
OR
- Remove indexing

Parent Issue: #114

**Comment by Jasperabez** [comment]
@AY2425S1-CS2103-F13-2/developers would be nice to get some opinions on this

**Comment by C5hives** [comment]
I will recommend:
- If viewing an event, `unassign` only takes in an `Index` for the nested `Vendor` list currently displayed.
- If viewing a vendor, `unassign` only takes in an `Index` for the nested `Event` list current displayed.

The current model keeps track of the selected `Event` and `Vendor`, so `model.unassignVendorFromEvent` already has half the information to work with.

As for tracking the indexes in the nested list, it's currently being done by the UI components now (which is bad).

Would it be possible to shift that logic into `ModelManager`? The list can be observable for UI to track it and update the display when necessary?

**Comment by hanscau** [comment]
I think that is fine, will need to wait for issue #106 to merge first before doing the refactor
