### ISSUE TITLE
Wrong assignable events/vendors when traversing between views

### ISSUE THREAD

**Issue by Jasperabez** [AY2425S1-CS2103-F13-2/tp#194]
After viewing an event/vendor that has event/vendor assigned, if run view multiple times on unique event and vendor assignable events would no longer display the correct "assignables" and even shows some assigned items.

Furthermore the relative indexing on these items seems to have some mismatch although the command output seems to refer to the correct item (e.g view v/5 - which is roy displays roy on the command output but the actual viewing is wrong)

![Screenshot_20241107_045739](https://github.com/user-attachments/assets/d9ef6cf7-9be4-4218-9c89-abdd3094f6fb)

**Comment by Jasperabez** [comment]
@hanscau seems like is a new behaviour that doesn't exist at 6a4e3f5ec3f5a6dcc397606fcc4e26b338735389

**Comment by Jasperabez** [comment]
@AY2425S1-CS2103-F13-2/developers should we fix this in next milestone? since I'll assume this to classify as a bug.
Maybe we open up a forum issue for this this check whether this classify as a bug?

**Comment by C5hives** [comment]
This is a pretty catastrophic bug to leave in for `v1.5` though. Are you able to diagnose the root cause of this bug (and #203 as well)?

I don't think opening a forum issue will help. If it comes down to it, we can list this as a known issue, but it won't look very pretty.
