### ISSUE TITLE
Weird indexing of assigned event / vendor list

### ISSUE THREAD

**Issue by kahsuann** [AY2425S1-CS2103-F13-2/tp#203]
Similar to #194 

Indexes of Assigned events and vendors are no longer consistent, and don't function as it should anymore. In the screenshot, when trying to unassign 6 (which is the given index), operation fails.

<img width="959" alt="image" src="https://github.com/user-attachments/assets/be82e14c-7c8c-4dc9-aa04-08ba9a16cd9b">

because of the issue Jabez pointed out where the command prompt and view details show different events / vendors, assigning 'pizza party' to the currently view tam assigns to benjamin instead. tam's assigned events remain unchanged and its assignable events no longer include 'pizza party'
<img width="959" alt="image" src="https://github.com/user-attachments/assets/422fc950-d24e-46ca-8159-83535f457b6a">

**Comment by Jasperabez** [comment]
can you test whether this issue persist by checking out the commit I comment under #194?

**Comment by Jasperabez** [comment]
resolved by #219
