### ISSUE TITLE
Tag cannot display long inputs

### ISSUE THREAD

**Issue by kahsuann** [AY2425S1-CS2103-F13-2/tp#205]
<img width="486" alt="image" src="https://github.com/user-attachments/assets/1482c9fd-3789-4990-8fce-6d5f5175823e">

I think we can consider wrapping the text like description or restrict tag length since tags shouldn't be too long anyway. What do yall think

**Comment by hanscau** [comment]
Alternatively, we can limit the max character for tags

**Comment by C5hives** [comment]
I think limiting the length of the tag is simplest. Truncating or obfuscating the actual tag makes the tag kinda useless.
