### ISSUE TITLE
[PE-D][Tester B] unclear documentation of command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-2/tp#255]
Inconsistent CLI format in contrast to other commands. However, could be confusing into why a space was used to separate v/ <vendor> where as in other commands such as view there was no such separation for example: view v/1

![image.png](https://raw.githubusercontent.com/Hoodini231/ped/main/files/b656d7bf-4c49-4e6b-a168-e51b836d13c4.png)

Contrasting command usasge as well:

![image.png](https://raw.githubusercontent.com/Hoodini231/ped/main/files/10829a33-f67e-4187-8e45-f84b0fa6c96a.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Hoodini231/ped#2

**Comment by Jasperabez** [comment]
To be addressed by #327

**Comment by Jasperabez** [comment]
just have to standardize all `find` the same format
