### ISSUE TITLE
[PE-D][Tester A] Adding duplicate vendors/events with extra whitespaces between names is allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-2/tp#261]
The app allows users to add vendors/events with the same information, but with extra whitespaces between names.

**Example:**

- create v/ n/Hong Lim Trading Pte. Ltd. p/67412943 d/Specialises in lighting effects. t/stage-crew
- create v/ n/Hong␣␣␣␣␣Lim Trading Pte. Ltd. p/67412943 d/Specialises in lighting effects. t/stage-crew

**Note:** ␣ denotes whitespace

**Expected output:**
`This vendor already exists in EventTory.`

**Actual output:**
New vendor added: Hong␣␣␣␣␣Lim Trading Pte. Ltd.; Phone: 67412943; Description: Specialises in lighting effects.; Tags: [stage-crew]

If this was the intended behavior, then the user guide should have specified the constraint. See the [course website](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-pe.html#feature-flaws-2:~:text=If%20you%20app%20has%20a%20duplicate%20detection%20feature%2C%20make%20sure%20its%20limitations%20are%20made%20clear%20to%20the%20user%20so%20that%20users%20are%20not%20led%20to%20believe%20that%20duplicates%20are%20being%20detected%20while%20many%20potential%20duplicate%20cases%20go%20undetected.%20Otherwise%2C%20it%20can%20be%20considered%20a%20type.FeatureFlaw.) for more info.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Gra7ityIC3/ped#4

**Comment by Jasperabez** [comment]
to be addressed by #318
