### ISSUE TITLE
[PE-D][Tester B] Unrelated vendor rating in documentation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-2/tp#263]
Found a glossary index for vendor rating leading me to believe there was a rating function within the program. However, it is never used again outside the glossary thus it is redundant in the documentation.

![image.png](https://raw.githubusercontent.com/Hoodini231/ped/main/files/33050677-b98c-4891-adc5-c35709c3b19c.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Hoodini231/ped#3

**Comment by Jasperabez** [comment]
used in user stories iirc
