### ISSUE TITLE
[PE-D][Tester C] Duplicate phone number

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-2/tp#266]
![image.png](https://raw.githubusercontent.com/LingZiyann/ped/main/files/82e72e54-c546-4c9b-b5ac-62f2776cf319.png)
Different vendors can share the same phone number. Kinda dont make sense that 2 different vendors have same phone number? Could clarify this in the user guide

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: LingZiyann/ped#3

**Comment by Jasperabez** [comment]
Is an assumption that vendors can't have duplicate numbers.
For example Prism tv and Prism fans can share the same number however it is good to include what we define as duplicates in DG and UG.

**Comment by Jasperabez** [comment]
To be addressed by #325
