### ISSUE TITLE
[PE-D][Tester D] Names with '/' are not allowed in event creation

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-2/tp#290]
Names with "s/o" or "d/o" will not be treated as valid inputs and can cause misrepresentation for some people who have these abbreviations in their names.

Input command:
`create e/ n/Balakrishnan s/o Balakrishnan BDay Party on/11-11-2024`

Result:
![image.png](https://raw.githubusercontent.com/valhrd/ped/main/files/abe7da94-f693-4995-8ca8-6a02e6dc71c7.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: valhrd/ped#6

**Comment by Jasperabez** [comment]
To be addressed by #322
