### ISSUE TITLE
[PE-D][Tester A] Invalid example for `edit` command in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-2/tp#292]
The notes for the `edit` command specifies:

- The operation will succeed even if the specified vendor/event is not visible on screen.
  - e.g. `edit v/1` is run after `view v/2`. Even though the 1st vendor will not be visible, it can still be edited.

Here, `edit v/1` is invalid because there were no parameters specified.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Gra7ityIC3/ped#12

**Comment by Jasperabez** [comment]
to be addressed by #321
