### ISSUE TITLE
[PE-D][Tester D] Description can have Chinese characters but not tags

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-2/tp#297]
Description is able to take in Chinese characters but Tags are not.
I understand that tags are using toLowerCase() to check for duplicate tags but what if someone speaks only Chinese. Is he only supposed to use the description to keep track or perhaps lock everything down just to English.

Command to run:
`edit v/1 t/非常好`

Result:
![image.png](https://raw.githubusercontent.com/valhrd/ped/main/files/adf536cd-fe89-43a2-b5d4-449938b891cd.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: valhrd/ped#8

**Comment by Jasperabez** [comment]
can tackle this in the doc by saying is meant for english users only but also in future improvements on adding language support

**Comment by Jasperabez** [comment]
to be addressed by #320
