### ISSUE TITLE
[PE-D][Tester E] Exception not accurate when assigning a vendor to an event, when there are no more vendors

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-2/tp#301]
Assuming this situation:

![Screenshot 2024-11-08 at 5.44.08 PM.png](https://raw.githubusercontent.com/vicelyav/ped/main/files/3fbf9fb8-206d-4a91-b11e-9d758ba7d857.png)

If i type `assign 1` the error message will be:
The specified vendor is already assigned to this Event

Instead of no more vendors.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: vicelyav/ped#10

**Comment by Jasperabez** [comment]
don't this is a major problem
