### ISSUE TITLE
[PE-D][Tester C] Better feedback message for invalid dates

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-2/tp#309]
![image.png](https://raw.githubusercontent.com/LingZiyann/ped/main/files/f5a68bfb-937d-456f-9565-614b83a87eec.png)
Date provided is of uuuu-MM-dd format but rejected, feedback message isn't clear why it was rejected

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: LingZiyann/ped#10

**Comment by Jasperabez** [comment]
imagine having a 13 month in the calendar wild, can safely ignore this I think unless want to add in the doc for clarification on the valid months and days.... @AY2425S1-CS2103-F13-2/developers

**Comment by Jasperabez** [comment]
similar to #274 (30 days in April)
