### ISSUE TITLE
[PE-D][Tester E] Command prefix is case-sensitive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-2/tp#312]
Right now the prefix is case-sensitive, so it is not that convenient to the user. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: vicelyav/ped#15

**Comment by Jasperabez** [comment]
can add in DG as future enhancement

**Comment by Jasperabez** [comment]
to be addressed by #320
