### ISSUE TITLE
[PE-D][Tester A] UI component section in DG not updated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-2/tp#315]
References like `PersonListPanel` and `Person` are not updated.

![image.png](https://raw.githubusercontent.com/Gra7ityIC3/ped/main/files/dae97dc4-4497-4689-a7ac-7eb6b98c8675.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Gra7ityIC3/ped#14

**Comment by Jasperabez** [comment]
To be addressed by #327
