### ISSUE TITLE
Name allow duplicates with case sensitivity and white spaces 

### ISSUE THREAD

**Issue by Jasperabez** [AY2425S1-CS2103-F13-2/tp#318]
What the course website says:
> A: If the case-sensitivity of a feature does not follow the real world, it is considered a feature flaw (i.e, the design of the feature is not optimal). The best you can do in v1.6 is to document this behavior clearly in the UG.
An exception is when the UG clearly states the case sensitivity but the actual feature implementation doesn't follow it, in which case it is a bug and can be fixed.

Brought up by issues: #282, #279, #261, #258
Action: TBD

**Comment by Jasperabez** [comment]
Gonna add a section into planned enhancements to address this

**Comment by hanscau** [comment]
Fixing it is considered a feature change?

**Comment by Jasperabez** [comment]
Addressed by #331
