### ISSUE TITLE
Evaluate/Improve UML diagrams 

### ISSUE THREAD

**Issue by Jasperabez** [AY2425S1-CS2103-F13-2/tp#324]
Can consider the following suggested UML changes (if makes sense)
Details: #304, #303, #281

**Comment by C5hives** [comment]
For #281, you could argue that it was a documentation bug inherited from AB3. The notation taught in the course definitely doesn't use `<<>>` to denote a label.
![image](https://github.com/user-attachments/assets/50df829a-f473-4dc2-9201-56b5fa7ce1f7)

Trivial to change so I think we can address it.

**Comment by Jasperabez** [comment]
aightz let's do that, btw can't use the inherit from ab3 as a reason... yeahh..

**Comment by Jasperabez** [comment]
@kevin-pek fix labels and split into smaller diagrams

**Comment by hanscau** [comment]
Changes to be made:
- Remove low level fields in the model class diagram
- Remove extra better OOP diagram
- UI class diagram remove UiPart
- Sequence diagram is too complicated, split into different functions
