### ISSUE TITLE
Rework of Current Feature Specification to Capitalize on Current Tokenizer Capabilities

### ISSUE THREAD

**Issue by C5hives** [AY2425S1-CS2103-F13-2/tp#77]
Our current feature specification is tailored to be more human-readable but is hard to implement with the existing tokenizer.

The main issue stems from how some commands can have different behaviors depending on whether it is directed at a `Vendor` or an `Event`.

In order to avoid reinventing the wheel, some modifications could be made to our feature specification to fully take advantage of the current tokenizer implementation.

### Possible Modifications
- `list` is unchanged.
- `list events` to `list e/`
- `list vendors` to `list v/`
Note: having a prefix with nothing after it is valid. It can possibly throw an error only if you specify it to do so.

- `create vendor <name> contact/ <phone_number>` to `create v/<name> contact/<phone number>`
- `create event <name> on/ <date>` to `create e/<name> on/<date>`

- `view event <event_id>` to `view e/<event_id>`
- `view event <event_name>` to `view e/<event_name>`
- `view vendor <vendor_id>` to `view v/<vendor_id>`
- `view vendor <vendor_name>` to `view v/<vendor_name>`

- `assign vendor 2 event 4` to `assign v/2 e/4`
- `assign event 4 vendor 2` to `assign e/4 v/2` (order still doesn't matter)

Feel free to share your opinion on this and let me know if I had missed out on any commands.

**Comment by hanscau** [comment]
`edit` command is not reworked yet
