### ISSUE TITLE
Add support for storing list of associations

### ISSUE THREAD

**Issue by kevin-pek** [AY2425S1-CS2103-F13-2/tp#96]
Currently, the application does not support saving the list of associations between vendors and events. We need to extend the storage functionality to store this data in the same JSON format used for other data.

**Comment by C5hives** [comment]
Given how `Event` and `Vendor` objects are currently stored in .json format, I'm not sure if there's a method to store their associations without re-serializing the `Event` and `Vendor` objects—which will lead to quite a bit of data duplication in the .json file.

Just something to consider

**Comment by kevin-pek** [comment]
Would be tricky to implement this. Am thinking of saving it based off the array index of the vendors and events. Otherwise might be better to introduce a unique id field to the `Vendor` and `Event` models.
